### ISSUE TITLE
build的時候發生錯誤

### ISSUE THREAD

**Issue by ghchen** [jspzyhl/AzurLane5.1-bcDec#1]
build cmd:
```
cmake .
msbuild bcDecoder.sln
```
會出現"系統找不到指定的路徑。"的錯誤

應該把 **CMakeLists.txt** 的 16行

`COMMAND ${PROJECT_SOURCE_DIR}/src/msvcbuild.bat`

改成

`COMMAND ${PROJECT_SOURCE_DIR}/msvcbuild.bat`

再 build 一次就可以了

**Comment by jspzyhl** [comment]
已发预编译文件
